# Generated by Django 4.2.2 on 2023-07-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='опыт работы'),
        ),
    ]
