# Generated by Django 4.2.2 on 2023-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vacancy_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='type_of_employment',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('partial', 'partial'), ('piecework', 'piecework')], default='complete', max_length=10, null=True, verbose_name='тип занятости'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Скилл'),
        ),
    ]
